name: Deploy

on:
  push:
    branches:
    - develop

permissions:
  contents: read
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v4

    - name: install the gcloud cli
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        INSTANCE_UNIX_SOCKET: ${{ secrets.INSTANCE_UNIX_SOCKET }}
        CONNECTION_NAME: ${{ secrets.CONNECTION_NAME }}
        VERSION: ee850a89e0871ca46916078fe6d514b22f64b14d1ee76046c08f710cc13c182b
        AUTHURL: ${{ secrets.AUTHURL_dev }}
        SERVICEKEY: ${{ secrets.SERVICEKEY }}
      run: |-
        gcloud run deploy api-produit-develop --image europe-west9-docker.pkg.dev/$GOOGLE_PROJECT/api-produit/image-api-produit@sha256:$VERSION --set-env-vars DATABASE_HOST=$DATABASE_HOST --set-env-vars DATABASE_USER=$DATABASE_USER --set-env-vars DATABASE_PASSWORD=$DATABASE_PASSWORD --set-env-vars INSTANCE_UNIX_SOCKET=$INSTANCE_UNIX_SOCKET --set-env-vars SERVICEKEY=$SERVICEKEY --set-env-vars AUTHURL=$AUTHURL --add-cloudsql-instances $CONNECTION_NAME --region europe-west9 --platform managed --allow-unauthenticated
